version: '3'
services:
  backend:
    image: ruby:3.1
    container_name: my_sinatra_backend
    volumes:
      - ./my-sinatra-app:/usr/src/app
    working_dir: /usr/src/app
    command: bash -c "bundle install && bundle exec ruby app.rb -o 0.0.0.0"
    ports:
      - "4567:4567"

  frontend:
    image: node:lts-alpine
    container_name: my_vue_frontend
    volumes:
      - ./my-vue-app:/usr/src/app
    working_dir: /usr/src/app
    command: ["sh", "-c", "npm install && npm run serve"]
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "8080:8080"
