# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem 'nio4r', '2.5.9'
gem 'puma'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'sinatra-cross_origin'
